name: "Hello world"
description: "My first real add-on!"
version: "1.1.2"
slug: "poolsync"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
#  mqtt_url: 'mqtt://auto_username:auto_password@auto_hostname'
#  mqtt_options: ''
  user: ''
  password: ''
#  disarm_code: ''
#  enable_cameras: true
#  enable_modes: false
#  enable_panic: false
#  branch: addon
#  debug: ring-*
#  location_ids:
    - ''