name: "Hello world"
description: "My first real add-on!"
version: "1.1.0"
slug: "poolsync"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
network:
  8000/TCP: The webserver port (Not used for Ingress)